### PR TITLE
Virginia

### PR DESCRIPTION
**Pull request by virginia-m**
Solved first gradient problem.
Added .gitignore file

### CODE REVIEW

**Comment by josh146** [comment]
Hi @virginia-m, to submit your solution, you will need to use the challenge.qhack.ai. More details are available here: https://github.com/XanaduAI/QHack/tree/main/QML_Challenges#submitting-your-solutions

**Comment by virginia-m** [comment]
Hi Josh! I'm sorry, this was a silly mistake - I wanted to create the pull request to my fork that I made of the repo which I share with my team! I accidentally clicked through the pull requests to quickly! Sorry  about that! :)

**Comment by josh146** [comment]
No worries, I will attempt to delete this pull request so that others don't chance upon your solution :)

**Comment by virginia-m** [comment]
Thank you! :)

Also, thanks so much for putting all this together! Me and my team are having a blast! :)

**Pull request closed without merging**
